version: "3.7"
services:
        build:
                build: src/docker/build
                image: net.ofnir/shadow-cljs-build
                ports:
                        - "127.0.0.1:3333:3333"
                        - "127.0.0.1:9630:9630"
                        - "127.0.0.1:3449:3449"
                volumes:
                        - ".:/build:z"
